name: Ayush CI
on:
  push:
    branches: [ "sum_two" ]
  pull_request:
    branches: [ "sum_two" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install packages
        run: make install
